wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    t:
      1:
      - 1
      4: 3.6.13
      5: 0.10.31
      8:
      - 5
fold:
  desc: null
  value: 1
percent:
  desc: null
  value: 10
total_step:
  desc: null
  value: 180000
work_dirs:
  desc: null
  value: work_dirs/${cfg_name}/${percent}/${fold}
